//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using MySql.Data.MySqlClient;
namespace PenjualanPembelian_LIB
{
    public class Jabatan
    {
        public virtual string IdJabatan
        {
            get;
            set;
        }

        public virtual string NamaJabatan
        {
            get;
            set;
        }
        public Jabatan()
        {
            IdJabatan = "";
            NamaJabatan = "";
        }

        public Jabatan(string jab, string nam)
        {
            IdJabatan = jab;
            NamaJabatan = nam;
        }



        public static string TambahData(Jabatan jab)
        {
            string sql = "INSERT INTO jabatan(IdJabatan, Nama) VALUES ('" + jab.IdJabatan + "','" + jab.NamaJabatan.Replace("'", "\\'") + "')";

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah SQL : " + sql;
            }
        }

        public static string UbahData(Jabatan jab)
        {
            string sql = "UPDATE jabatan SET Nama = '" + jab.NamaJabatan.Replace("'", "\\'") + "' WHERE IdJabatan = '" + jab.IdJabatan + "'";

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
        public static string HapusData(Jabatan jab)
        {
            string sql = "DELETE FROM jabatan WHERE IdJabatan = '" + jab.IdJabatan + "'";

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }

        public static string BacaData(string kriteria, string nilaiKriteria, List<Jabatan> listHasilData)
        {
            string sql = "";

            //jika tidak ada kriteria yang diisikan 
            if (kriteria == "")
            {
                sql = "SELECT * FROM jabatan";
            }
            else
            {
                sql = "SELECT * FROM jabatan WHERE " + kriteria + " LIKE '%" + nilaiKriteria + "%'";
            }
            try
            {
                MySqlDataReader hasilData = Koneksi.JalankanPerintahQuery(sql);
                while (hasilData.Read() == true)
                {
                    Jabatan jb = new Jabatan();
                    jb.IdJabatan = hasilData.GetValue(0).ToString();
                    jb.NamaJabatan = hasilData.GetValue(1).ToString();

                    listHasilData.Add(jb);
                }
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
         public static string CetakNota(string pKriteria, string pNilaiKriteria, string pNamaFile)
        {
            try
            {
                List<Jabatan> listJabatan = new List<Jabatan>();

                //baca data nota tertentu yang akan dicetak
                string hasilBaca = Jabatan.BacaData(pKriteria, pNilaiKriteria, listJabatan);

                //simpan dulu isi nota yang akan ditampilkan ke objek file (streamwriter)
                StreamWriter file = new StreamWriter(pNamaFile);
                for (int i = 0; i < listJabatan.Count; i++)
                {
                    file.WriteLine("{0,5} | {1,5}", listJabatan[i].IdJabatan, listJabatan[i].NamaJabatan);
                }
                file.Close();
                //cetak ke printer
                Cetak c = new Cetak(pNamaFile, "Courier New", 9, 10, 10, 10, 10);
                c.CetakKePrinter("tulisan");
                return "1";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
    }
}

