//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using System.IO;
using MySql.Data.MySqlClient;

namespace PenjualanPembelian_LIB
{
    public class Kategori
    {
        private string kodeKategori;

        public string KodeKategori
        {
            get { return kodeKategori; }
            set { kodeKategori = value; }
        }
        private string nama;

        public string Nama
        {
            get { return nama; }
            set { nama = value; }
        }

        public Kategori() 
        {
            kodeKategori = "";
            nama = "";
        }

        public Kategori(string Kat, string nam) 
        {
            kodeKategori = Kat;
            nama = nam;
        }

        
        public static string TambahData(Kategori kat) 
        {
            string sql = "INSERT INTO kategori(KodeKategori, Nama) VALUES ('" + kat.KodeKategori +"','"+kat.Nama.Replace("'","\\'") +"')";

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex) {
                return ex.Message + ". Perintah SQL : " + sql;
            }
        }

        public static string UbahData(Kategori kat)
        {
            string sql = "UPDATE kategori SET Nama = '" + kat.Nama.Replace("'", "\\'") + "' WHERE KodeKategori = '" + kat.kodeKategori + "'";

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
        public static string HapusData(Kategori kat)
        {
            string sql = "DELETE FROM kategori WHERE KodeKategori = '" + kat.kodeKategori + "'";

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            } 
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
      
        public static string BacaData(string kriteria, string nilaiKriteria, List<Kategori> listHasilData) 
        {
            string sql = "";

            //jika tidak ada kriteria yang diisikan 
            if (kriteria == "")
            {
                sql = "SELECT * FROM kategori";
            }
            else 
            {
                sql = "SELECT * FROM kategori WHERE " + kriteria +" LIKE '%" + nilaiKriteria + "%'";
            }
            try 
            {
                MySqlDataReader hasilData = Koneksi.JalankanPerintahQuery(sql);
                while(hasilData.Read() == true)
                {
                    Kategori kt = new Kategori();
                    kt.kodeKategori = hasilData.GetValue(0).ToString();
                    kt.Nama = hasilData.GetValue(1).ToString();

                    listHasilData.Add(kt);
                }
                return "1";
            }
            catch(MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
        public static string CetakNota(string pKriteria, string pNilaiKriteria, string pNamaFile)
        {
            try
            {
                List<Kategori> listKategori = new List<Kategori>();

                //baca data nota tertentu yang akan dicetak
                string hasilBaca = Kategori.BacaData(pKriteria, pNilaiKriteria, listKategori);

                //simpan dulu isi nota yang akan ditampilkan ke objek file (streamwriter)
                StreamWriter file = new StreamWriter(pNamaFile);
                for (int i = 0; i < listKategori.Count; i++)
                {
                    file.WriteLine("{0,5} | {1,5}", listKategori[i].KodeKategori, listKategori[i].Nama);
                }
                file.Close();
                //cetak ke printer
                Cetak c = new Cetak(pNamaFile, "Courier New", 9, 10, 10, 10, 10);
                c.CetakKePrinter("tulisan");
                return "1";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        public string GenerateKode()
        {
            Koneksi k = new Koneksi();
            k.Connect();
            //tuliskan perintah SQL yang akan dijalankan
            string sql = "SELECT KodeKategori FROM Kategori ORDER BY KodeKategori DESC LIMIT 1";
            //Buat MySqlCommand 
            MySqlCommand c = new MySqlCommand(sql, k.KoneksiDB);
            try
            {
                //Gunakan MySqlDataReader dan ExecuteReader untuk menjalankan perintah SELECT
                MySqlDataReader data = c.ExecuteReader();

                //jika data reader bisa terbaca (selama masih ada data)
                if (data.Read() == true)
                {
                    //mendapatkan kode kategori dari hasil data reader
                    int kdTerbaru = int.Parse(data.GetValue(0).ToString()) + 1;
                    kodeKategori = kdTerbaru.ToString();

                    //Format kode kategori
                    if (kodeKategori.Length == 1)
                    {
                        kodeKategori = "0" + kodeKategori;
                    }
                }

                //hapus MySqlCommand setelah selesai
                c.Dispose();
                //hapus data reader setelah selesai
                data.Dispose();

                return "sukses";
            }
            catch (Exception e)
            {
                return e.Message;
            }
        }
    }
}

