//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using MySql.Data.MySqlClient;
using System.Diagnostics;

namespace PenjualanPembelian_LIB
{
    public class Pegawai
    {
        public virtual int KodePegawai
        {
            get;
            set;
        }

        public virtual string Nama
        {
            get;
            set;
        }

        public virtual string Username
        {
            get;
            set;
        }

        public virtual string Password
        {
            get;
            set;
        }

        public virtual DateTime TglLahir
        {
            get;
            set;
        }

        public virtual string Alamat
        {
            get;
            set;
        }

        public virtual int Gaji
        {
            get;
            set;
        }

        public virtual Jabatan Jabatan
        {
            get;
            set;
        }
        public Pegawai()
        {
            KodePegawai = 0;
            Nama = "";
            Username = "";
            Password = "";
            Alamat = "";
            Gaji = 0;
            TglLahir = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day);
        }

        public Pegawai(int kode, string nam, DateTime tgllhr, string almt, int gj, string usrnm, string pass, Jabatan jbtn)
        {
            KodePegawai = kode;
            Nama = nam;
            Username = usrnm;
            Password = pass;
            TglLahir = tgllhr;
            Alamat = almt;
            Gaji = gj;
            Jabatan = jbtn;
        }

        public static string TambahData(Pegawai peg)
        {
            string sql = "INSERT INTO pegawai(KodePegawai, Nama, TglLahir, Alamat, Gaji, Username, Password, IdJabatan) VALUES (" + peg.KodePegawai + ",'" + peg.Nama.Replace("'", "\\'") + "','" + peg.TglLahir.ToString("yyyy-MM-dd") + "','" + peg.Alamat.Replace("'", "\\'") + "'," + peg.Gaji + ",'" + peg.Username.Replace("'", "\\'") + "','" + peg.Password.Replace("'", "\\'") + "','" + peg.Jabatan.IdJabatan + "')";

            try
            {
                //insert ke tabel pegawai
                Koneksi.JalankanPerintahDML(sql);

                //ambil nama server dan nama database dengan method GetNamaServer dan GetNamaDatabase
                string namaServer = Koneksi.GetNamaServer();
                string namaDatabase = Koneksi.GetNamaDatabase();

                //create user baru di mysql dengan menggunakan method buatUserBaru
                string hasilBuatUSer = Pegawai.BuatUserBaru(peg, namaServer);

                if (hasilBuatUSer != "1")//jika tidak berhasil membuat user baru
                {
                    return "Gagal membuat user baru. Pesan kesalahan : " + hasilBuatUSer;
                }
                else
                {
                    //beri hak akses kepada user tsb dengan menggunakan method berihakakses
                    string hasilHakAkses = Pegawai.BeriHakAkses(peg, namaServer, namaDatabase);
                    if (hasilHakAkses != "1")
                    {
                        return "Gagal memberikan hak akses baru. Pesan kesalahan : " + hasilHakAkses;
                    }
                    else {
                        return "1";
                    }
                }
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah SQL : " + sql;
            }
        }
        public static string UbahData(Pegawai peg)
        {
            string sql = "UPDATE pegawai SET Nama = '" + peg.Nama.Replace("'", "\\'") + "', TglLahir = '" + peg.TglLahir.ToString("yyyy-MM-dd")  + "', Alamat = '" + peg.Alamat.Replace("'", "\\'") + "', Gaji = " + peg.Gaji + ", Username = '" + peg.Username.Replace("'", "\\'") + "', Password = '" + peg.Password.Replace("'", "\\'")  +"', IdJabatan = '" + peg.Jabatan.IdJabatan + "' WHERE KodePegawai = " + peg.KodePegawai;

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                string namaServer = Koneksi.GetNamaServer();
                string namaDatabase = Koneksi.GetNamaDatabase();

                //create user baru di mysql dengan menggunakan method buatUserBaru
                string UbahPassUser = Pegawai.UbahPassUser(peg, namaServer);
                if (UbahPassUser != "1")//jika tidak berhasil membuat user baru
                {
                    return "Gagal membuat user baru. Pesan kesalahan : " + UbahPassUser;
                }
                else
                {
                    return "1";
                }
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
        public static string HapusData(Pegawai peg)
        {
            string sql = "DELETE FROM pegawai WHERE KodePegawai = '" + peg.KodePegawai + "'";

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                string namaServer = Koneksi.GetNamaServer();
                string namaDatabase = Koneksi.GetNamaDatabase();

                //create user baru di mysql dengan menggunakan method buatUserBaru
                string HapusUser = Pegawai.HapusUser(peg, namaServer);
                if (HapusUser != "1")//jika tidak berhasil membuat user baru
                {
                    return "Gagal membuat user baru. Pesan kesalahan : " + HapusUser;
                }
                else
                {
                    return "1";
                }
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }

        Microsoft.Office.Interop.Excel.Application excel;
        Microsoft.Office.Interop.Excel.Workbook worKbooK;
        Microsoft.Office.Interop.Excel.Worksheet worKsheeT;
        Microsoft.Office.Interop.Excel.Range celLrangE;

        public void printsajaBeli(string filename, string periode)
        {
            try
            {
                //BUAT PRINT
                ProcessStartInfo info = new ProcessStartInfo();
                info.Verb = "print";
                info.FileName = @filename;
                info.CreateNoWindow = true;
                info.WindowStyle = ProcessWindowStyle.Hidden;

                Process p = new Process();
                p.StartInfo = info;
                p.Start();

                p.WaitForInputIdle();
                System.Threading.Thread.Sleep(3000);
            }
            catch (Exception ex)
            {

                String msg = ex.Message;
            }
        }
        public void printLaporanPembelian(String filename,String periode)
        {
            try
            {
                excel = new Microsoft.Office.Interop.Excel.Application();
                excel.Visible = false;
                excel.DisplayAlerts = false;
                worKbooK = excel.Workbooks.Add(Type.Missing);


                worKsheeT = (Microsoft.Office.Interop.Excel.Worksheet)worKbooK.ActiveSheet;
                worKsheeT.Name = "Report";

                worKsheeT.Range[worKsheeT.Cells[1, 1], worKsheeT.Cells[1, 6]].Merge();
                worKsheeT.Cells[1, 1] = "Laporan Pembelian";
                worKsheeT.Cells.Font.Size = 15;

                worKsheeT.Cells[2, 1] = "Tanggal";
                worKsheeT.Cells[2, 2] = "NoNota";
                worKsheeT.Cells[2, 3] = "Nama";
                worKsheeT.Cells[2, 4] = "jumlah";
                worKsheeT.Cells[2, 5] = "Harga";
                worKsheeT.Cells[2, 6] = "Total";



                Microsoft.Office.Interop.Excel.Style style = excel.ActiveWorkbook.Styles.Add("NewStyle");

                style.Font.Name = "Verdana";
                style.Font.Size = 12;
                style.Font.Bold = true;
                style.HorizontalAlignment = Microsoft.Office.Interop.Excel.XlHAlign.xlHAlignCenter;

                Koneksi k = new Koneksi();
                k.Connect();


                int baris = 3;
                String q = "SELECT DATE_FORMAT(Tanggal,'%d-%M-%Y') as Tanggal,b.Nama,nd.Jumlah,nd.Harga,(nd.Harga*nd.Jumlah) as Subtotal,nb.NoNota " +
                            "FROM notabeli nb " +
                            "INNER JOIN notabelidetil nd ON (nb.NoNota=nd.NoNota) "+
                            "INNER JOIN barang b ON (b.KodeBarang=nd.KodeBarang) " +
                            "WHERE DATE_FORMAT(Tanggal,'%Y-%M')=?periode";
                MySqlCommand c = new MySqlCommand(q, k.KoneksiDB);
                c.Parameters.Add(new MySqlParameter("periode",periode));
                MySqlDataReader rd = c.ExecuteReader();
                int total = 0;
                while (rd.Read())
                {
                    worKsheeT.Cells[baris, 1] = rd["Tanggal"];
                    worKsheeT.Cells[baris, 2] = rd["NoNota"];
                    worKsheeT.Cells[baris, 3] = rd["Nama"];
                    worKsheeT.Cells[baris, 4] = rd["Jumlah"];
                    worKsheeT.Cells[baris, 5] = rd["Harga"];
                    worKsheeT.Cells[baris, 6] = rd["Subtotal"];
                    total = total + Int32.Parse(rd["Subtotal"]+"");
                    baris = baris + 1;
                }

                worKsheeT.Cells[baris, 6] = total;

                Microsoft.Office.Interop.Excel.Range angkaStyles = excel.get_Range("E3:F" + baris);
                angkaStyles.NumberFormat = "##,#";


                Microsoft.Office.Interop.Excel.Range rangeStyles = excel.get_Range("A1:F20");
                Microsoft.Office.Interop.Excel.Range rangeStyles2 = excel.get_Range("A1:F2");
                Microsoft.Office.Interop.Excel.Range rangeStyles3 = excel.get_Range("A1:F" + baris);


                rangeStyles2.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();

                rangeStyles.Columns.AutoFit();
                rangeStyles3.Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous;
                rangeStyles3.Borders.Weight = Microsoft.Office.Interop.Excel.XlBorderWeight.xlThin;
                k.KoneksiDB.Close();
              

                worKbooK.SaveAs(filename);
                worKbooK.Close();
                excel.Quit();

                //BUAT PRINT
                /*ProcessStartInfo info = new ProcessStartInfo();
                info.Verb = "print";
                info.FileName = @filename;
                info.CreateNoWindow = true;
                info.WindowStyle = ProcessWindowStyle.Hidden;

                Process p = new Process();
                p.StartInfo = info;
                p.Start();

                p.WaitForInputIdle();
                System.Threading.Thread.Sleep(3000);*/

            }
            catch (Exception ex)
            {

                String msg = ex.Message;
                String abc = "aa";
            }
            finally
            {
                worKsheeT = null;
                celLrangE = null;
                worKbooK = null;
            }
        }

        //masih belum
        public void printLaporanPenjualan(String filename, String periode)
        {
            try
            {
                excel = new Microsoft.Office.Interop.Excel.Application();
                excel.Visible = false;
                excel.DisplayAlerts = false;
                worKbooK = excel.Workbooks.Add(Type.Missing);


                worKsheeT = (Microsoft.Office.Interop.Excel.Worksheet)worKbooK.ActiveSheet;
                worKsheeT.Name = "Report";

                worKsheeT.Range[worKsheeT.Cells[1, 1], worKsheeT.Cells[1, 6]].Merge();
                worKsheeT.Cells[1, 1] = "Laporan Penjualan";
                worKsheeT.Cells.Font.Size = 15;

                worKsheeT.Cells[2, 1] = "Tanggal";
                worKsheeT.Cells[2, 2] = "NoNota";
                worKsheeT.Cells[2, 3] = "Nama Barang";
                worKsheeT.Cells[2, 4] = "Jumlah";
                worKsheeT.Cells[2, 5] = "Harga";
                worKsheeT.Cells[2, 6] = "Total";
                //worKsheeT.Cells[2, 5] = "Kategori";



                Microsoft.Office.Interop.Excel.Style style = excel.ActiveWorkbook.Styles.Add("NewStyle");

                style.Font.Name = "Verdana";
                style.Font.Size = 12;
                style.Font.Bold = true;
                style.HorizontalAlignment = Microsoft.Office.Interop.Excel.XlHAlign.xlHAlignCenter;

                Koneksi k = new Koneksi();
                k.Connect();


                int baris = 3;
                String q = "SELECT DATE_FORMAT(Tanggal,'%d-%M-%Y') as Tanggal,b.Nama,nd.Jumlah,nd.Harga,(nd.Harga*nd.Jumlah) as Subtotal,nb.NoNota " +
                            "FROM notajual nb " +
                            "INNER JOIN notajualdetil nd ON (nb.NoNota=nd.NoNota) " +
                            "INNER JOIN barang b ON (b.KodeBarang=nd.KodeBarang) " +
                            "WHERE DATE_FORMAT(Tanggal,'%Y-%M')=?periode";
                MySqlCommand c = new MySqlCommand(q, k.KoneksiDB);
                c.Parameters.Add(new MySqlParameter("periode", periode));
                MySqlDataReader rd = c.ExecuteReader();
                int total = 0;
                while (rd.Read())
                {
                    worKsheeT.Cells[baris, 1] = rd["Tanggal"];
                    worKsheeT.Cells[baris, 2] = rd["NoNota"];
                    worKsheeT.Cells[baris, 3] = rd["Nama"];
                    worKsheeT.Cells[baris, 4] = rd["Jumlah"];
                    worKsheeT.Cells[baris, 5] = rd["Harga"];
                    worKsheeT.Cells[baris, 6] = rd["Subtotal"];
                    total = total + Int32.Parse(rd["Subtotal"] + "");
                    baris = baris + 1;
                }

                worKsheeT.Cells[baris, 6] = total;

                Microsoft.Office.Interop.Excel.Range angkaStyles = excel.get_Range("E3:F" + baris);
                angkaStyles.NumberFormat = "##,#";


                Microsoft.Office.Interop.Excel.Range rangeStyles = excel.get_Range("A1:F20");
                Microsoft.Office.Interop.Excel.Range rangeStyles2 = excel.get_Range("A1:F2");
                Microsoft.Office.Interop.Excel.Range rangeStyles3 = excel.get_Range("A1:F" + baris);


                rangeStyles2.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();

                //rangeStyles.Value2 = "'Style Test";
                //rangeStyles.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();
                //rangeStyles3.BorderAround2();
                rangeStyles3.Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous;
                rangeStyles3.Borders.Weight = Microsoft.Office.Interop.Excel.XlBorderWeight.xlThin;
                k.KoneksiDB.Close();


                worKbooK.SaveAs(filename);
                worKbooK.Close();
                excel.Quit();

                ProcessStartInfo info = new ProcessStartInfo();
                info.Verb = "print";
                info.FileName = @filename;
                info.CreateNoWindow = true;
                info.WindowStyle = ProcessWindowStyle.Hidden;

                Process p = new Process();
                p.StartInfo = info;
                p.Start();

                p.WaitForInputIdle();
                System.Threading.Thread.Sleep(3000);
                //if (false == p.CloseMainWindow())
                //p.Kill();

            }
            catch (Exception ex)
            {

                String msg = ex.Message;
                String abc = "aa";
            }
            finally
            {
                worKsheeT = null;
                celLrangE = null;
                worKbooK = null;
            }
        }
        public void printBarang(String filename)
        {
            try
            {
                excel = new Microsoft.Office.Interop.Excel.Application();
                excel.Visible = false;
                excel.DisplayAlerts = false;
                worKbooK = excel.Workbooks.Add(Type.Missing);


                worKsheeT = (Microsoft.Office.Interop.Excel.Worksheet)worKbooK.ActiveSheet;
                worKsheeT.Name = "Report";

                worKsheeT.Range[worKsheeT.Cells[1, 1], worKsheeT.Cells[1, 4]].Merge();
                worKsheeT.Cells[1, 1] = "Laporan Barang";
                worKsheeT.Cells.Font.Size = 15;
                
                worKsheeT.Cells[2, 1] = "Kode Barang";
                worKsheeT.Cells[2, 2] = "Nama Barang";
                worKsheeT.Cells[2, 3] = "Harga Barang";
                worKsheeT.Cells[2, 4] = "Stok";
                //worKsheeT.Cells[2, 5] = "Kategori";



                Microsoft.Office.Interop.Excel.Style style = excel.ActiveWorkbook.Styles.Add("NewStyle");

                style.Font.Name = "Verdana";
                style.Font.Size = 12;
                style.Font.Bold = true;
                style.HorizontalAlignment = Microsoft.Office.Interop.Excel.XlHAlign.xlHAlignCenter;

                Koneksi k = new Koneksi();
                k.Connect();


                int baris = 3;
                String q = "SELECT * FROM barang";
                MySqlCommand c = new MySqlCommand(q, k.KoneksiDB);
                MySqlDataReader rd = c.ExecuteReader();
                while (rd.Read())
                {
                    worKsheeT.Cells[baris, 1] = rd["KodeBarang"];
                    worKsheeT.Cells[baris, 2] = rd["Nama"];
                    worKsheeT.Cells[baris, 3] = rd["HargaJual"];
                    worKsheeT.Cells[baris, 4] = rd["Stok"];
                    baris = baris + 1;
                }

                Microsoft.Office.Interop.Excel.Range angkaStyles = excel.get_Range("A3:D"+baris);
                angkaStyles.NumberFormat = "##,#";
                Microsoft.Office.Interop.Excel.Range rangeStyles = excel.get_Range("A1:D20");
                Microsoft.Office.Interop.Excel.Range rangeStyles2 = excel.get_Range("A1:D2");
                Microsoft.Office.Interop.Excel.Range rangeStyles3 = excel.get_Range("A1:D"+baris);


                rangeStyles2.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();

                //rangeStyles.Value2 = "'Style Test";
                //rangeStyles.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();
                //rangeStyles3.BorderAround2();
                rangeStyles3.Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous;
                rangeStyles3.Borders.Weight = Microsoft.Office.Interop.Excel.XlBorderWeight.xlThin;
                k.KoneksiDB.Close();
                /*
                MySqlConnection mc = new MySqlConnection(Koneksi.strCon);
                MySqlCommand cmd = new MySqlCommand(q, mc);
                MySqlDataReader rd = cmd.ExecuteReader();


                int barisS= 2;
                while (rd.Read())
                {
                    worKsheeT.Cells[barisS, 1] = rd["KodeBarang"];
                    worKsheeT.Cells[barisS, 2] = rd["NamaBarang"];
                    worKsheeT.Cells[barisS, 3] = rd["HargaJual"];
                    worKsheeT.Cells[barisS, 4] = rd["Stok"];
                    barisS++;
                    //worKsheeT.Cells[2, 5] = "Kategori";
                }*/



                //DateTime dt = DateTime.Now;
              
                worKbooK.SaveAs(filename);
                worKbooK.Close();
                excel.Quit();

                /*ProcessStartInfo info = new ProcessStartInfo();
                info.Verb = "print";
                info.FileName = @filename;
                info.CreateNoWindow = true;
                info.WindowStyle = ProcessWindowStyle.Hidden;

                Process p = new Process();
                p.StartInfo = info;
                p.Start();

                p.WaitForInputIdle();
                System.Threading.Thread.Sleep(3000);*/
                //if (false == p.CloseMainWindow())
                //p.Kill();

            }
            catch (Exception ex)
            {
                

            }
            finally
            {
                worKsheeT = null;
                celLrangE = null;
                worKbooK = null;
            }
        }
        public void printKategori(String filename)
        {
            try
            {
                excel = new Microsoft.Office.Interop.Excel.Application();
                excel.Visible = false;
                excel.DisplayAlerts = false;
                worKbooK = excel.Workbooks.Add(Type.Missing);


                worKsheeT = (Microsoft.Office.Interop.Excel.Worksheet)worKbooK.ActiveSheet;
                worKsheeT.Name = "ReportKategori";

                worKsheeT.Range[worKsheeT.Cells[1, 1], worKsheeT.Cells[1, 2]].Merge();
                worKsheeT.Cells[1, 1] = "Daftar Kategori";
                worKsheeT.Cells.Font.Size = 15;

                worKsheeT.Cells[2, 1] = "Kode Pelanggan";
                worKsheeT.Cells[2, 2] = "Nama";
                //worKsheeT.Cells[2, 5] = "Kategori";



                Microsoft.Office.Interop.Excel.Style style = excel.ActiveWorkbook.Styles.Add("NewStyle");

                style.Font.Name = "Verdana";
                style.Font.Size = 12;
                style.Font.Bold = true;
                style.HorizontalAlignment = Microsoft.Office.Interop.Excel.XlHAlign.xlHAlignCenter;

                Koneksi k = new Koneksi();
                k.Connect();


                int baris = 3;
                String q = "SELECT * FROM Kategori";
                MySqlCommand c = new MySqlCommand(q, k.KoneksiDB);
                MySqlDataReader rd = c.ExecuteReader();
                while (rd.Read())
                {
                    worKsheeT.Cells[baris, 1] = rd["KodeKategori"];
                    worKsheeT.Cells[baris, 2] = rd["Nama"];
                    baris = baris + 1;
                }

                Microsoft.Office.Interop.Excel.Range angkaStyles = excel.get_Range("A3:D" + baris);
                angkaStyles.NumberFormat = "##,#";
                Microsoft.Office.Interop.Excel.Range rangeStyles = excel.get_Range("A1:B20");
                Microsoft.Office.Interop.Excel.Range rangeStyles2 = excel.get_Range("A1:D2");
                Microsoft.Office.Interop.Excel.Range rangeStyles3 = excel.get_Range("A1:B" + baris);


                rangeStyles2.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();

                //rangeStyles.Value2 = "'Style Test";
                //rangeStyles.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();
                //rangeStyles3.BorderAround2();
                rangeStyles3.Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous;
                rangeStyles3.Borders.Weight = Microsoft.Office.Interop.Excel.XlBorderWeight.xlThin;
                k.KoneksiDB.Close();
                /*
                MySqlConnection mc = new MySqlConnection(Koneksi.strCon);
                MySqlCommand cmd = new MySqlCommand(q, mc);
                MySqlDataReader rd = cmd.ExecuteReader();


                int barisS= 2;
                while (rd.Read())
                {
                    worKsheeT.Cells[barisS, 1] = rd["KodeBarang"];
                    worKsheeT.Cells[barisS, 2] = rd["NamaBarang"];
                    worKsheeT.Cells[barisS, 3] = rd["HargaJual"];
                    worKsheeT.Cells[barisS, 4] = rd["Stok"];
                    barisS++;
                    //worKsheeT.Cells[2, 5] = "Kategori";
                }*/



                //DateTime dt = DateTime.Now;

                worKbooK.SaveAs(filename);
                worKbooK.Close();
                excel.Quit();

                ProcessStartInfo info = new ProcessStartInfo();
                info.Verb = "print";
                info.FileName = @filename;
                info.CreateNoWindow = true;
                info.WindowStyle = ProcessWindowStyle.Hidden;

                Process p = new Process();
                p.StartInfo = info;
                p.Start();

                p.WaitForInputIdle();
                System.Threading.Thread.Sleep(3000);
                //if (false == p.CloseMainWindow())
                //p.Kill();
            }
            catch (Exception ex)
            {


            }
            finally
            {
                worKsheeT = null;
                celLrangE = null;
                worKbooK = null;

            }
        }
        public void printPelanggan(String filename)
        {
            try
            {
                excel = new Microsoft.Office.Interop.Excel.Application();
                excel.Visible = false;
                excel.DisplayAlerts = false;
                worKbooK = excel.Workbooks.Add(Type.Missing);


                worKsheeT = (Microsoft.Office.Interop.Excel.Worksheet)worKbooK.ActiveSheet;
                worKsheeT.Name = "ReportPelanggan";

                worKsheeT.Range[worKsheeT.Cells[1, 1], worKsheeT.Cells[1, 4]].Merge();
                worKsheeT.Cells[1, 1] = "Daftar Pelanggan";
                worKsheeT.Cells.Font.Size = 15;

                worKsheeT.Cells[2, 1] = "Kode Pelanggan";
                worKsheeT.Cells[2, 2] = "Nama";
                worKsheeT.Cells[2, 3] = "Alamat";
                worKsheeT.Cells[2, 4] = "Telepon";
                //worKsheeT.Cells[2, 5] = "Kategori";



                Microsoft.Office.Interop.Excel.Style style = excel.ActiveWorkbook.Styles.Add("NewStyle");

                style.Font.Name = "Verdana";
                style.Font.Size = 12;
                style.Font.Bold = true;
                style.HorizontalAlignment = Microsoft.Office.Interop.Excel.XlHAlign.xlHAlignCenter;

                Koneksi k = new Koneksi();
                k.Connect();


                int baris = 3;
                String q = "SELECT * FROM Pelanggan";
                MySqlCommand c = new MySqlCommand(q, k.KoneksiDB);
                MySqlDataReader rd = c.ExecuteReader();
                while (rd.Read())
                {
                    worKsheeT.Cells[baris, 1] = rd["KodePelanggan"];
                    worKsheeT.Cells[baris, 2] = rd["Nama"];
                    worKsheeT.Cells[baris, 3] = rd["Alamat"];
                    worKsheeT.Cells[baris, 4] = rd["Telepon"];
                    baris = baris + 1;
                }

                Microsoft.Office.Interop.Excel.Range angkaStyles = excel.get_Range("A3:D" + baris);
                angkaStyles.NumberFormat = "##,#";
                Microsoft.Office.Interop.Excel.Range rangeStyles = excel.get_Range("A1:D20");
                Microsoft.Office.Interop.Excel.Range rangeStyles2 = excel.get_Range("A1:D2");
                Microsoft.Office.Interop.Excel.Range rangeStyles3 = excel.get_Range("A1:D" + baris);


                rangeStyles2.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();

                //rangeStyles.Value2 = "'Style Test";
                //rangeStyles.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();
                //rangeStyles3.BorderAround2();
                rangeStyles3.Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous;
                rangeStyles3.Borders.Weight = Microsoft.Office.Interop.Excel.XlBorderWeight.xlThin;
                k.KoneksiDB.Close();
                /*
                MySqlConnection mc = new MySqlConnection(Koneksi.strCon);
                MySqlCommand cmd = new MySqlCommand(q, mc);
                MySqlDataReader rd = cmd.ExecuteReader();


                int barisS= 2;
                while (rd.Read())
                {
                    worKsheeT.Cells[barisS, 1] = rd["KodeBarang"];
                    worKsheeT.Cells[barisS, 2] = rd["NamaBarang"];
                    worKsheeT.Cells[barisS, 3] = rd["HargaJual"];
                    worKsheeT.Cells[barisS, 4] = rd["Stok"];
                    barisS++;
                    //worKsheeT.Cells[2, 5] = "Kategori";
                }*/



                //DateTime dt = DateTime.Now;

                worKbooK.SaveAs(filename);
                worKbooK.Close();
                excel.Quit();

                ProcessStartInfo info = new ProcessStartInfo();
                info.Verb = "print";
                info.FileName = @filename;
                info.CreateNoWindow = true;
                info.WindowStyle = ProcessWindowStyle.Hidden;

                Process p = new Process();
                p.StartInfo = info;
                p.Start();

                p.WaitForInputIdle();
                System.Threading.Thread.Sleep(3000);
                //if (false == p.CloseMainWindow())
                //p.Kill();
                }
            catch (Exception ex)
            {
                

            }
            finally
            {
                worKsheeT = null;
                celLrangE = null;
                worKbooK = null;
            
            }
        }
        public void printSuplier(String filename)
        {
            try
            {
                excel = new Microsoft.Office.Interop.Excel.Application();
                excel.Visible = false;
                excel.DisplayAlerts = false;
                worKbooK = excel.Workbooks.Add(Type.Missing);


                worKsheeT = (Microsoft.Office.Interop.Excel.Worksheet)worKbooK.ActiveSheet;
                worKsheeT.Name = "ReportSuplier";

                worKsheeT.Range[worKsheeT.Cells[1, 1], worKsheeT.Cells[1, 4]].Merge();
                worKsheeT.Cells[1, 1] = "Daftar Suplier";
                worKsheeT.Cells.Font.Size = 15;

                worKsheeT.Cells[2, 1] = "Kode Suplier";
                worKsheeT.Cells[2, 2] = "Nama";
                worKsheeT.Cells[2, 3] = "Alamat";
                worKsheeT.Cells[2, 4] = "Telepon";
                //worKsheeT.Cells[2, 5] = "Kategori";



                Microsoft.Office.Interop.Excel.Style style = excel.ActiveWorkbook.Styles.Add("NewStyle");

                style.Font.Name = "Verdana";
                style.Font.Size = 12;
                style.Font.Bold = true;
                style.HorizontalAlignment = Microsoft.Office.Interop.Excel.XlHAlign.xlHAlignCenter;

                Koneksi k = new Koneksi();
                k.Connect();


                int baris = 3;
                String q = "SELECT * FROM Supplier";
                MySqlCommand c = new MySqlCommand(q, k.KoneksiDB);
                MySqlDataReader rd = c.ExecuteReader();
                while (rd.Read())
                {
                    worKsheeT.Cells[baris, 1] = rd["KodeSupplier"];
                    worKsheeT.Cells[baris, 2] = rd["Nama"];
                    worKsheeT.Cells[baris, 3] = rd["Alamat"];
                    worKsheeT.Cells[baris, 4] = rd["Telepon"];
                    baris = baris + 1;
                }

                Microsoft.Office.Interop.Excel.Range angkaStyles = excel.get_Range("A3:D" + baris);
                angkaStyles.NumberFormat = "##,#";
                Microsoft.Office.Interop.Excel.Range rangeStyles = excel.get_Range("A1:D20");
                Microsoft.Office.Interop.Excel.Range rangeStyles2 = excel.get_Range("A1:D2");
                Microsoft.Office.Interop.Excel.Range rangeStyles3 = excel.get_Range("A1:D" + baris);


                rangeStyles2.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();

                //rangeStyles.Value2 = "'Style Test";
                //rangeStyles.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();
                //rangeStyles3.BorderAround2();
                rangeStyles3.Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous;
                rangeStyles3.Borders.Weight = Microsoft.Office.Interop.Excel.XlBorderWeight.xlThin;
                k.KoneksiDB.Close();
                /*
                MySqlConnection mc = new MySqlConnection(Koneksi.strCon);
                MySqlCommand cmd = new MySqlCommand(q, mc);
                MySqlDataReader rd = cmd.ExecuteReader();


                int barisS= 2;
                while (rd.Read())
                {
                    worKsheeT.Cells[barisS, 1] = rd["KodeBarang"];
                    worKsheeT.Cells[barisS, 2] = rd["NamaBarang"];
                    worKsheeT.Cells[barisS, 3] = rd["HargaJual"];
                    worKsheeT.Cells[barisS, 4] = rd["Stok"];
                    barisS++;
                    //worKsheeT.Cells[2, 5] = "Kategori";
                }*/



                //DateTime dt = DateTime.Now;

                worKbooK.SaveAs(filename);
                worKbooK.Close();
                excel.Quit();

                ProcessStartInfo info = new ProcessStartInfo();
                info.Verb = "print";
                info.FileName = @filename;
                info.CreateNoWindow = true;
                info.WindowStyle = ProcessWindowStyle.Hidden;

                Process p = new Process();
                p.StartInfo = info;
                p.Start();

                p.WaitForInputIdle();
                System.Threading.Thread.Sleep(3000);
                //if (false == p.CloseMainWindow())
                //p.Kill();
            }
            catch (Exception ex)
            {


            }
            finally
            {
                worKsheeT = null;
                celLrangE = null;
                worKbooK = null;

            }
        }
        public void printPegawai(String filename)
        {
            try
            {
                excel = new Microsoft.Office.Interop.Excel.Application();
                excel.Visible = false;
                excel.DisplayAlerts = false;
                worKbooK = excel.Workbooks.Add(Type.Missing);


                worKsheeT = (Microsoft.Office.Interop.Excel.Worksheet)worKbooK.ActiveSheet;
                worKsheeT.Name = "Report Pegawai";

                worKsheeT.Range[worKsheeT.Cells[1, 1], worKsheeT.Cells[1, 4]].Merge();
                worKsheeT.Cells[1, 1] = "Laporan Pegawai";
                worKsheeT.Cells.Font.Size = 15;

                worKsheeT.Cells[2, 1] = "Kode Pegawai";
                worKsheeT.Cells[2, 2] = "Nama";
                worKsheeT.Cells[2, 3] = "Tanggal Lahir";
                worKsheeT.Cells[2, 4] = "Alamat";
                worKsheeT.Cells[2, 5] = "Gaji";
                worKsheeT.Cells[2, 6] = "Username";
                worKsheeT.Cells[2, 7] = "Password";
                worKsheeT.Cells[2, 8] = "IdJabatan";
                //worKsheeT.Cells[2, 5] = "Kategori";



                Microsoft.Office.Interop.Excel.Style style = excel.ActiveWorkbook.Styles.Add("NewStyle");

                style.Font.Name = "Verdana";
                style.Font.Size = 12;
                style.Font.Bold = true;
                style.HorizontalAlignment = Microsoft.Office.Interop.Excel.XlHAlign.xlHAlignCenter;

                Koneksi k = new Koneksi();
                k.Connect();


                int baris = 3;
                String q = "SELECT * FROM Pegawai";
                MySqlCommand c = new MySqlCommand(q, k.KoneksiDB);
                MySqlDataReader rd = c.ExecuteReader();
                while (rd.Read())
                {
                    worKsheeT.Cells[baris, 1] = rd["KodePegawai"];
                    worKsheeT.Cells[baris, 2] = rd["Nama"];
                    worKsheeT.Cells[baris, 3] = rd["TglLahir"];
                    worKsheeT.Cells[baris, 4] = rd["Alamat"];
                    worKsheeT.Cells[baris, 5] = rd["Gaji"];
                    worKsheeT.Cells[baris, 6] = rd["Username"];
                    worKsheeT.Cells[baris, 7] = rd["Password"];
                    worKsheeT.Cells[baris, 8] = rd["IdJabatan"];
                    /*if (worKsheeT.Cells[baris, 8] = "J1")
                    {
                        worKsheeT.Cells[baris, 8] = "Pegawai Pembelian";
                    }
                    else if (worKsheeT.Cells[baris, 8] = "J2")
                    {
                        worKsheeT.Cells[baris, 8] = "Kasir";
                    }
                    else if (worKsheeT.Cells[baris, 8] = "J3")
                    {
                        worKsheeT.Cells[baris, 8] = "Manager";
                    }*/

                    baris = baris + 1;
                }

                Microsoft.Office.Interop.Excel.Range angkaStyles = excel.get_Range("A3:H" + baris);
                angkaStyles.NumberFormat = "##,#";
                Microsoft.Office.Interop.Excel.Range rangeStyles = excel.get_Range("A1:H20");
                Microsoft.Office.Interop.Excel.Range rangeStyles2 = excel.get_Range("A1:H2");
                Microsoft.Office.Interop.Excel.Range rangeStyles3 = excel.get_Range("A1:H" + baris);


                rangeStyles2.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();

                //rangeStyles.Value2 = "'Style Test";
                //rangeStyles.Style = "NewStyle";
                rangeStyles.Columns.AutoFit();
                //rangeStyles3.BorderAround2();
                rangeStyles3.Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous;
                rangeStyles3.Borders.Weight = Microsoft.Office.Interop.Excel.XlBorderWeight.xlThin;
                k.KoneksiDB.Close();
                /*
                MySqlConnection mc = new MySqlConnection(Koneksi.strCon);
                MySqlCommand cmd = new MySqlCommand(q, mc);
                MySqlDataReader rd = cmd.ExecuteReader();


                int barisS= 2;
                while (rd.Read())
                {
                    worKsheeT.Cells[barisS, 1] = rd["KodeBarang"];
                    worKsheeT.Cells[barisS, 2] = rd["NamaBarang"];
                    worKsheeT.Cells[barisS, 3] = rd["HargaJual"];
                    worKsheeT.Cells[barisS, 4] = rd["Stok"];
                    barisS++;
                    //worKsheeT.Cells[2, 5] = "Kategori";
                }*/



                //DateTime dt = DateTime.Now;

                worKbooK.SaveAs(filename);
                worKbooK.Close();
                excel.Quit();

                /*ProcessStartInfo info = new ProcessStartInfo();
                info.Verb = "print";
                info.FileName = @filename;
                info.CreateNoWindow = true;
                info.WindowStyle = ProcessWindowStyle.Hidden;

                Process p = new Process();
                p.StartInfo = info;
                p.Start();

                p.WaitForInputIdle();
                System.Threading.Thread.Sleep(3000);*/
                //if (false == p.CloseMainWindow())
                //p.Kill();

            }
            catch (Exception ex)
            {


            }
            finally
            {
                worKsheeT = null;
                celLrangE = null;
                worKbooK = null;
            }
        }
        public static MySqlDataReader JalankanPerintahQuery(string pSql)
        {
            Koneksi k = new Koneksi();
            k.Connect();

            MySqlCommand c = new MySqlCommand(pSql, k.KoneksiDB);

            MySqlDataReader hasil = c.ExecuteReader();

            return hasil;
        }
        public static string BacaData(string kriteria, string nilaiKriteria, List<Pegawai> listHasilData)
        {
            string sql = "";

            //jika tidak ada kriteria yang diisikan 
            if (kriteria == "")
            {
                sql = "SELECT P.KodePegawai, P.Nama, P.TglLahir, P.Alamat, P.Gaji, P.Username, P.Password, P.IdJabatan, J.Nama AS NamaJabatan FROM pegawai P INNER JOIN jabatan J ON P.IdJabatan = J.IdJabatan";
            }
            else
            {
                sql = "SELECT P.KodePegawai, P.Nama, P.TglLahir, P.Alamat, P.Gaji, P.Username, P.Password, P.IdJabatan, J.Nama AS NamaJabatan FROM pegawai P INNER JOIN jabatan J ON P.IdJabatan = J.IdJabatan WHERE " + kriteria + " LIKE '%" + nilaiKriteria + "%'";
            }
            try
            {
                MySqlDataReader hasilData = Koneksi.JalankanPerintahQuery(sql);
                listHasilData.Clear();//kosongi isi list dulu
                while (hasilData.Read() == true)//selama masih ada data
                {
                    Pegawai pgw = new Pegawai();
                    pgw.KodePegawai = int.Parse(hasilData.GetValue(0).ToString());
                    pgw.Nama = hasilData.GetValue(1).ToString();
                    pgw.TglLahir = DateTime.Parse(hasilData.GetValue(2).ToString());
                    pgw.Alamat = hasilData.GetValue(3).ToString();
                    pgw.Gaji = int.Parse(hasilData.GetValue(4).ToString());
                    pgw.Username = hasilData.GetValue(5).ToString();
                    pgw.Password = hasilData.GetValue(6).ToString();
                    //ciptakan objek untuk kategori barang
                    Jabatan namJab = new Jabatan(hasilData.GetValue(7).ToString(), hasilData.GetValue(8).ToString());
                    pgw.Jabatan = namJab;

                    listHasilData.Add(pgw);
                }
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
        public static string GenerateKode(out int pHasilKode)
        {
            //format kode : x(x : nomor urut pegawai)
            //untuk membuat no urut maka dapatkan kode pegawai terakhir (terbesar) dari pegawai tertentu
            string sql = "SELECT MAX(KodePegawai) FROM pegawai";
            pHasilKode = 0;
            try
            {
                MySqlDataReader hasilData = Koneksi.JalankanPerintahQuery(sql);

                if (hasilData.Read() == true)
                {// jika berhasil membaca data (ditemukan data ditabel pegawai)
                    if (hasilData.GetValue(0).ToString() != "")
                    {//jika hasil query tidak kosong (sudah ada data pegawai)
                        int kodeTerbaru = int.Parse(hasilData.GetValue(0).ToString()) + 1;
                        pHasilKode = kodeTerbaru;
                    }
                    else
                    {
                        // jika tidak ditemukan data di tabel pegawai maka kode terbaru = 1
                        pHasilKode = 1;
                    }
                }
                return "1";
            }
            catch(Exception e) {
                return e.Message;
            }
        }
        public static string BuatUserBaru(Pegawai pPegawai, string pNamaServer)
        {
            string sql = "CREATE USER '" + pPegawai.Username + "'@'" + pNamaServer + "' IDENTIFIED BY '" + pPegawai.Password + "'";
            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch(MySqlException ex) {
                return ex.Message + ". perintah sql : " + sql;
            }
        }
        public static string UbahPassUser(Pegawai pPegawai, string pNamaServer)
        {
            string sql = "SET PASSWORD FOR '" + pPegawai.Username + "'@'" + pNamaServer + "'=PASSWORD('" + pPegawai.Password + "')";
            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". perintah sql : " + sql;
            }
        }
        public static string HapusUser(Pegawai pPegawai, string pNamaServer)
        {
            string sql = "DROP USER '" + pPegawai.Username + "'@'" + pNamaServer + "'";
            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". perintah sql : " + sql;
            }
        }
        public static string BeriHakAkses(Pegawai pPegawai, string pNamaServer, string pNamaDatabase) { 
            String sql = "GRANT ALL PRIVILEGES ON " + pNamaDatabase + ".* TO '" + pPegawai.Username + "'@'" + pNamaServer + "'";
            try {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch(MySqlException ex){
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
        public static string CetakNota(string pKriteria, string pNilaiKriteria, string pNamaFile)
        {
            try
            {
                List<Pegawai> listPegawai = new List<Pegawai>();

                //baca data nota tertentu yang akan dicetak
                string hasilBaca = Pegawai.BacaData(pKriteria, pNilaiKriteria, listPegawai);

                //simpan dulu isi nota yang akan ditampilkan ke objek file (streamwriter)
                StreamWriter file = new StreamWriter(pNamaFile);
                for (int i = 0; i < listPegawai.Count; i++)
                {
                    file.WriteLine("{0,5} | {1,5} | {2,5} | {3,5} | {4,5} | {5,5} | {6,5}", listPegawai[i].KodePegawai, listPegawai[i].Nama, listPegawai[i].TglLahir, listPegawai[i].Alamat, listPegawai[i].Gaji, listPegawai[i].Username, listPegawai[i].Jabatan.IdJabatan);
                }
                file.Close();
                //cetak ke printer
                Cetak c = new Cetak(pNamaFile, "Courier New", 9, 10, 10, 10, 10);
                c.CetakKePrinter("tulisan");
                return "1";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
    }
}

