//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using System.IO;
using MySql.Data.MySqlClient;

namespace PenjualanPembelian_LIB
{
    public class Supplier
    {
        public virtual int KodeSupplier
        {
            get;
            set;
        }

        public virtual string NamaSupplier
        {
            get;
            set;
        }

        public virtual string Alamat
        {
            get;
            set;
        }
        public Supplier() {
            KodeSupplier = 0;
            NamaSupplier = "";
            Alamat = "";
        }
        public Supplier(int pKodeSupplier, string pNamaSupplier, string pAlamat)
        {
            KodeSupplier = pKodeSupplier;
            NamaSupplier = pNamaSupplier;
            Alamat = pAlamat;
        }
        private static void JalankanPerintahDML(string pSql)
        {
            Koneksi k = new Koneksi();
            k.Connect();

            //buat mysqlcommand
            MySqlCommand c = new MySqlCommand(pSql, k.KoneksiDB);

            //gunakan executenonquery untuk menjalankan perintah insert/update/delete
            c.ExecuteNonQuery();
        }
        public static string TambahData(Supplier sup)
        {
            string sql = "INSERT INTO supplier(KodeSupplier, Nama, Alamat) VALUES (" + sup.KodeSupplier + ",'" + sup.NamaSupplier.Replace("'", "\\'") + "','" + sup.Alamat + "')";

            try
            {
                JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah SQL : " + sql;
            }
        }
        public static string UbahData(Supplier sup)
        {
            string sql = "UPDATE supplier SET Nama = '" + sup.NamaSupplier.Replace("'", "\\'") + "', Alamat = '" + sup.Alamat.Replace("'", "\\'") + "' WHERE KodeSupplier = " + sup.KodeSupplier;

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
        public static string HapusData(Supplier sup)
        {
            string sql = "DELETE FROM supplier WHERE KodeSupplier = " + sup.KodeSupplier;

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
        private static MySqlDataReader JalankanPerintahQuery(string pSql)
        {
            Koneksi k = new Koneksi();
            k.Connect();

            MySqlCommand c = new MySqlCommand(pSql, k.KoneksiDB);

            MySqlDataReader hasil = c.ExecuteReader();

            return hasil;
        }
        public static string BacaData(string kriteria, string nilaiKriteria, List<Supplier> listHasilData)
        {
            string sql = "";

            //jika tidak ada kriteria yang diisikan 
            if (kriteria == "")
            {
                sql = "SELECT * FROM supplier";
            }
            else
            {
                sql = "SELECT * FROM supplier WHERE " + kriteria + " LIKE '%" + nilaiKriteria + "%'";
            }
            try
            {
                MySqlDataReader hasilData = JalankanPerintahQuery(sql);
                while (hasilData.Read() == true)
                {
                    Supplier sup = new Supplier();
                    sup.KodeSupplier = int.Parse(hasilData.GetValue(0).ToString());
                    sup.NamaSupplier = hasilData.GetValue(1).ToString();
                    sup.Alamat = hasilData.GetValue(2).ToString();

                    listHasilData.Add(sup);
                }
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
        public static string GenerateKode(out int pHasilKode)
        {
            //format kode : x(x : nomor urut pegawai)
            //untuk membuat no urut maka dapatkan kode pegawai terakhir (terbesar) dari pegawai tertentu
            string sql = "SELECT MAX(KodeSupplier) FROM supplier";
            pHasilKode = 0;
            try
            {
                MySqlDataReader hasilData = Koneksi.JalankanPerintahQuery(sql);

                if (hasilData.Read() == true)
                {// jika berhasil membaca data (ditemukan data ditabel pegawai)
                    if (hasilData.GetValue(0).ToString() != "")
                    {//jika hasil query tidak kosong (sudah ada data pegawai)
                        int kodeTerbaru = int.Parse(hasilData.GetValue(0).ToString()) + 1;
                        pHasilKode = kodeTerbaru;
                    }
                    else
                    {
                        // jika tidak ditemukan data di tabel pegawai maka kode terbaru = 1
                        pHasilKode = 1;
                    }
                }
                return "1";
            }
            catch (Exception e)
            {
                return e.Message;
            }
        }
        public static string CetakNota(string pKriteria, string pNilaiKriteria, string pNamaFile)
        {
            try
            {
                List<Supplier> listSupplier = new List<Supplier>();

                //baca data nota tertentu yang akan dicetak
                string hasilBaca = Supplier.BacaData(pKriteria, pNilaiKriteria, listSupplier);

                //simpan dulu isi nota yang akan ditampilkan ke objek file (streamwriter)
                StreamWriter file = new StreamWriter(pNamaFile);
                for (int i = 0; i < listSupplier.Count; i++)
                {
                    file.WriteLine("{0,5} | {1,5} | {2,5}", listSupplier[i].KodeSupplier, listSupplier[i].NamaSupplier, listSupplier[i].Alamat);
                }
                file.Close();
                //cetak ke printer
                Cetak c = new Cetak(pNamaFile, "Courier New", 9, 10, 10, 10, 10);
                c.CetakKePrinter("tulisan");
                return "1";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
    }
}

